#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Created on Wed Jan 22 15:52:24 2014

Script to plot the seismograms generated by SPECFEM2D.
The arguments must be correct paths to existing 2D seismogram files or
an existing option (--hold, --grid)

@author: Alexis Bottero (alexis.bottero@gmail.com)
"""

from __future__ import (absolute_import, division, print_function)

import argparse

import numpy as np  # NumPy (multidimensional arrays, linear algebra, ...)
import matplotlib.pyplot as plt  # Matplotlib's pyplot: MATLAB-like syntax


parser = argparse.ArgumentParser(
    description='Plot seismograms generated by SPECFEM2D')
parser.add_argument('--hold', action='store_true',
                    help='Plot all seismograms on the same figure')
parser.add_argument('--grid', action='store_true',
                    help='Show a grid on the plot')
parser.add_argument('files', nargs='+', type=argparse.FileType('r'),
                    help='Files to be plotted')
args = parser.parse_args()

for seismo in args.files:
    data = np.loadtxt(seismo)

    if not args.hold:
        plt.figure()
    plt.plot(data[:, 0], data[:, 1])
    plt.xlim(data[0, 0], data[-1, 0])
    plt.grid(args.grid)
    plt.hold(args.hold)
    if not args.hold:
        plt.title(seismo.name)

plt.show()
