#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Created on Wed Jan 22 15:52:24 2014

Script to plot the seismograms generated by SPECFEM2D.
The arguments must be correct paths to existing 2D seismogram files or 
an existing option (--hold, --grid)
     
@author: Alexis Bottero (alexis.bottero@gmail.com)
"""

### --- MODULES AND PACKAGES --- ###
import argparse

import numpy as np  # NumPy (multidimensional arrays, linear algebra, ...)
import matplotlib as mpl         # Matplotlib (2D/3D plotting library)
import matplotlib.pyplot as plt  # Matplotlib's pyplot: MATLAB-like syntax
from pylab import *              # Matplotlib's pylab interface


parser = argparse.ArgumentParser(
    description='Plot seismograms generated by SPECFEM2D')
parser.add_argument('--hold', action='store_true',
                    help='Plot all seismograms on the same figure')
parser.add_argument('--grid', action='store_true',
                    help='Show a grid on the plot')
parser.add_argument('files', nargs='+', type=argparse.FileType('r'),
                    help='Files to be plotted')
args = parser.parse_args()

for seismo in args.files:
    data = np.loadtxt(seismo)
    t,u = data[:,0],data[:,1]
    if not args.hold:
        figure()
    plt.plot(t,u)
    if args.grid:
        plt.grid(True)
    if args.hold:
        plt.hold(True)
    else:
        plt.hold(False)
        plt.title(seismo.name)
    plt.xlim([t[0],t[-1]])
plt.show()    
